// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/endpoint.dart';
import 'api_handlers/attachments.dart';
import 'api_handlers/auth.dart';
import 'api_handlers/note_settings.dart';
import 'api_handlers/notebooks.dart';
import 'api_handlers/notes.dart';
import 'api_handlers/reminders.dart';
import 'api_handlers/shared_notes.dart';
import 'api_handlers/user_settings.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_FnLevelStringMessageStringPtr =>
      wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerfnlevelStringmessageStringPtr;

  @protected
  FnLevelStringMessageString
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerfnlevelStringmessageString(
    dynamic raw,
  );

  @protected
  FnLevelStringMessageString
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerfnlevelStringmessageString(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  Attachment dco_decode_attachment(dynamic raw);

  @protected
  AuthResponse dco_decode_auth_response(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  Attachment dco_decode_box_autoadd_attachment(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  Note dco_decode_box_autoadd_note(dynamic raw);

  @protected
  NoteSettings dco_decode_box_autoadd_note_settings(dynamic raw);

  @protected
  Notebook dco_decode_box_autoadd_notebook(dynamic raw);

  @protected
  Reminder dco_decode_box_autoadd_reminder(dynamic raw);

  @protected
  SharedNote dco_decode_box_autoadd_shared_note(dynamic raw);

  @protected
  UserSettings dco_decode_box_autoadd_user_settings(dynamic raw);

  @protected
  CheckApiResult dco_decode_check_api_result(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<Attachment> dco_decode_list_attachment(dynamic raw);

  @protected
  List<Note> dco_decode_list_note(dynamic raw);

  @protected
  List<NoteSettings> dco_decode_list_note_settings(dynamic raw);

  @protected
  List<Notebook> dco_decode_list_notebook(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<Reminder> dco_decode_list_reminder(dynamic raw);

  @protected
  List<SharedNote> dco_decode_list_shared_note(dynamic raw);

  @protected
  Note dco_decode_note(dynamic raw);

  @protected
  NoteSettings dco_decode_note_settings(dynamic raw);

  @protected
  Notebook dco_decode_notebook(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  Attachment? dco_decode_opt_box_autoadd_attachment(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  Note? dco_decode_opt_box_autoadd_note(dynamic raw);

  @protected
  NoteSettings? dco_decode_opt_box_autoadd_note_settings(dynamic raw);

  @protected
  Notebook? dco_decode_opt_box_autoadd_notebook(dynamic raw);

  @protected
  Reminder? dco_decode_opt_box_autoadd_reminder(dynamic raw);

  @protected
  SharedNote? dco_decode_opt_box_autoadd_shared_note(dynamic raw);

  @protected
  UserSettings? dco_decode_opt_box_autoadd_user_settings(dynamic raw);

  @protected
  Reminder dco_decode_reminder(dynamic raw);

  @protected
  SharedNote dco_decode_shared_note(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UserSettings dco_decode_user_settings(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  FnLevelStringMessageString
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerfnlevelStringmessageString(
    SseDeserializer deserializer,
  );

  @protected
  FnLevelStringMessageString
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerfnlevelStringmessageString(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  Attachment sse_decode_attachment(SseDeserializer deserializer);

  @protected
  AuthResponse sse_decode_auth_response(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  Attachment sse_decode_box_autoadd_attachment(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  Note sse_decode_box_autoadd_note(SseDeserializer deserializer);

  @protected
  NoteSettings sse_decode_box_autoadd_note_settings(
    SseDeserializer deserializer,
  );

  @protected
  Notebook sse_decode_box_autoadd_notebook(SseDeserializer deserializer);

  @protected
  Reminder sse_decode_box_autoadd_reminder(SseDeserializer deserializer);

  @protected
  SharedNote sse_decode_box_autoadd_shared_note(SseDeserializer deserializer);

  @protected
  UserSettings sse_decode_box_autoadd_user_settings(
    SseDeserializer deserializer,
  );

  @protected
  CheckApiResult sse_decode_check_api_result(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<Attachment> sse_decode_list_attachment(SseDeserializer deserializer);

  @protected
  List<Note> sse_decode_list_note(SseDeserializer deserializer);

  @protected
  List<NoteSettings> sse_decode_list_note_settings(
    SseDeserializer deserializer,
  );

  @protected
  List<Notebook> sse_decode_list_notebook(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<Reminder> sse_decode_list_reminder(SseDeserializer deserializer);

  @protected
  List<SharedNote> sse_decode_list_shared_note(SseDeserializer deserializer);

  @protected
  Note sse_decode_note(SseDeserializer deserializer);

  @protected
  NoteSettings sse_decode_note_settings(SseDeserializer deserializer);

  @protected
  Notebook sse_decode_notebook(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  Attachment? sse_decode_opt_box_autoadd_attachment(
    SseDeserializer deserializer,
  );

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  Note? sse_decode_opt_box_autoadd_note(SseDeserializer deserializer);

  @protected
  NoteSettings? sse_decode_opt_box_autoadd_note_settings(
    SseDeserializer deserializer,
  );

  @protected
  Notebook? sse_decode_opt_box_autoadd_notebook(SseDeserializer deserializer);

  @protected
  Reminder? sse_decode_opt_box_autoadd_reminder(SseDeserializer deserializer);

  @protected
  SharedNote? sse_decode_opt_box_autoadd_shared_note(
    SseDeserializer deserializer,
  );

  @protected
  UserSettings? sse_decode_opt_box_autoadd_user_settings(
    SseDeserializer deserializer,
  );

  @protected
  Reminder sse_decode_reminder(SseDeserializer deserializer);

  @protected
  SharedNote sse_decode_shared_note(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UserSettings sse_decode_user_settings(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerfnlevelStringmessageString(
    FnLevelStringMessageString self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerfnlevelStringmessageString(
    FnLevelStringMessageString self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_attachment(Attachment self, SseSerializer serializer);

  @protected
  void sse_encode_auth_response(AuthResponse self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_attachment(
    Attachment self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_note(Note self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_note_settings(
    NoteSettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_notebook(Notebook self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_reminder(Reminder self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_shared_note(
    SharedNote self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_user_settings(
    UserSettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_check_api_result(
    CheckApiResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_attachment(
    List<Attachment> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_note(List<Note> self, SseSerializer serializer);

  @protected
  void sse_encode_list_note_settings(
    List<NoteSettings> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_notebook(List<Notebook> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_reminder(List<Reminder> self, SseSerializer serializer);

  @protected
  void sse_encode_list_shared_note(
    List<SharedNote> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_note(Note self, SseSerializer serializer);

  @protected
  void sse_encode_note_settings(NoteSettings self, SseSerializer serializer);

  @protected
  void sse_encode_notebook(Notebook self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_attachment(
    Attachment? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_note(Note? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_note_settings(
    NoteSettings? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_notebook(
    Notebook? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_reminder(
    Reminder? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_shared_note(
    SharedNote? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_user_settings(
    UserSettings? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_reminder(Reminder self, SseSerializer serializer);

  @protected
  void sse_encode_shared_note(SharedNote self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_user_settings(UserSettings self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerfnlevelStringmessageString(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerfnlevelStringmessageString(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerfnlevelStringmessageStringPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_motek_ui_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerfnlevelStringmessageString',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerfnlevelStringmessageString =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerfnlevelStringmessageStringPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerfnlevelStringmessageString(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerfnlevelStringmessageString(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerfnlevelStringmessageStringPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_motek_ui_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerfnlevelStringmessageString',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerfnlevelStringmessageString =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerfnlevelStringmessageStringPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
