// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Attachment {
  final String id;
  final String noteId;
  final String filename;
  final String url;
  final PlatformInt64 createdAt;

  const Attachment({
    required this.id,
    required this.noteId,
    required this.filename,
    required this.url,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      noteId.hashCode ^
      filename.hashCode ^
      url.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Attachment &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          noteId == other.noteId &&
          filename == other.filename &&
          url == other.url &&
          createdAt == other.createdAt;
}
