// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class AuthResponse {
  final bool success;
  final String message;
  final String token;
  final String refreshToken;

  const AuthResponse({
    required this.success,
    required this.message,
    required this.token,
    required this.refreshToken,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      message.hashCode ^
      token.hashCode ^
      refreshToken.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuthResponse &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          message == other.message &&
          token == other.token &&
          refreshToken == other.refreshToken;
}
