// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class SharedNote {
  final String userId;
  final String noteId;
  final String role;
  final PlatformInt64 grantedAt;

  const SharedNote({
    required this.userId,
    required this.noteId,
    required this.role,
    required this.grantedAt,
  });

  @override
  int get hashCode =>
      userId.hashCode ^ noteId.hashCode ^ role.hashCode ^ grantedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SharedNote &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          noteId == other.noteId &&
          role == other.role &&
          grantedAt == other.grantedAt;
}
