// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class UserSettings {
  final String id;
  final String userId;
  final String lang;
  final String theme;
  final String timezone;
  final bool notificationsEnabled;
  final String defaultSort;
  final String editorMode;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;

  const UserSettings({
    required this.id,
    required this.userId,
    required this.lang,
    required this.theme,
    required this.timezone,
    required this.notificationsEnabled,
    required this.defaultSort,
    required this.editorMode,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      userId.hashCode ^
      lang.hashCode ^
      theme.hashCode ^
      timezone.hashCode ^
      notificationsEnabled.hashCode ^
      defaultSort.hashCode ^
      editorMode.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserSettings &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          userId == other.userId &&
          lang == other.lang &&
          theme == other.theme &&
          timezone == other.timezone &&
          notificationsEnabled == other.notificationsEnabled &&
          defaultSort == other.defaultSort &&
          editorMode == other.editorMode &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}
